### 1. TEST REGISTER (Candidate)
POST http://13.205.65.243/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "android_test@example.com",
  "password": "password123",
  "phone": "9998887776",
  "role": "candidate"
}

### 2. TEST LOGIN
POST http://13.205.65.243/api/auth/login
Content-Type: application/json

{
  "email": "android_test@example.com",
  "password": "password123"
}