/**
 * ===============================
 * PERMISSIONS (Action Level)
 * ===============================
 * Used in RBAC middleware across the admin panel
 */
const PERMISSIONS = {
    // USER MANAGEMENT
    VIEW_USERS: "VIEW_USERS",
    BLOCK_USERS: "BLOCK_USERS",
    UNBLOCK_USERS: "UNBLOCK_USERS",
    EDIT_USERS: "EDIT_USERS",
    FLAG_FRAUD_USERS: "FLAG_FRAUD_USERS",

    // ADMIN MANAGEMENT
    MANAGE_ADMINS: "MANAGE_ADMINS",
    MANAGE_ROLES: "MANAGE_ROLES",
    VIEW_ADMINS: "VIEW_ADMINS",

    // COMPANY MANAGEMENT
    VIEW_COMPANIES: "VIEW_COMPANIES",
    VERIFY_COMPANIES: "VERIFY_COMPANIES",
    MANAGE_COMPANIES: "MANAGE_COMPANIES",

    // MEETING MANAGEMENT
    MEETING_VIEW: "MEETING_VIEW",
    MEETING_MANAGE: "MEETING_MANAGE",
    MEETING_DELETE: "MEETING_DELETE",

    // WEBINAR MANAGEMENT
    WEBINAR_VIEW: "WEBINAR_VIEW",
    WEBINAR_CREATE: "WEBINAR_CREATE",
    WEBINAR_EDIT: "WEBINAR_EDIT",
    WEBINAR_DELETE: "WEBINAR_DELETE",

    // JOB & ATS
    CREATE_JOBS: "CREATE_JOBS",
    APPROVE_JOBS: "APPROVE_JOBS",
    VIEW_JOBS: "VIEW_JOBS",
    MANAGE_JOBS: "MANAGE_JOBS",
    JOB_VIEW: "JOB_VIEW",
    JOB_MANAGE: "JOB_MANAGE",
    JOB_DELETE: "JOB_DELETE",
    VIEW_APPLICATIONS: "VIEW_APPLICATIONS",
    MANAGE_ATS: "MANAGE_ATS",

    // TUTORIAL MANAGEMENT
    TUTORIAL_CREATE: "TUTORIAL_CREATE",
    TUTORIAL_VIEW: "TUTORIAL_VIEW",
    TUTORIAL_EDIT: "TUTORIAL_EDIT",
    TUTORIAL_DELETE: "TUTORIAL_DELETE",

    // SKILL TRAINING
    SKILL_TRAINING_VIEW: "SKILL_TRAINING_VIEW",
    SKILL_TRAINING_CREATE: "SKILL_TRAINING_CREATE",
    SKILL_TRAINING_EDIT: "SKILL_TRAINING_EDIT",
    SKILL_TRAINING_DELETE: "SKILL_TRAINING_DELETE",

    // CANDIDATE PROFILES
    VIEW_CANDIDATE_PROFILES: "VIEW_CANDIDATE_PROFILES",
    MANAGE_CANDIDATE_PROFILES: "MANAGE_CANDIDATE_PROFILES",
    DELETE_CANDIDATE_PROFILES: "DELETE_CANDIDATE_PROFILES",

    // BILLING
    VIEW_PAYMENTS: "VIEW_PAYMENTS",
    MANAGE_REFUNDS: "MANAGE_REFUNDS",
    MANAGE_SUBSCRIPTIONS: "MANAGE_SUBSCRIPTIONS",
    PROCESS_REFUNDS: "PROCESS_REFUNDS",

    // REPORTS & AUDIT
    VIEW_REPORTS: "VIEW_REPORTS",
    VIEW_REVENUE: "VIEW_REVENUE",
    VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
    VIEW_SECURITY_LOGS: "VIEW_SECURITY_LOGS",
    FINANCIAL_ADMIN: "FINANCIAL_ADMIN",

    // AI MANAGEMENT
    VIEW_AI_USAGE: "VIEW_AI_USAGE",
    MANAGE_AI_LIMITS: "MANAGE_AI_LIMITS",

    // SYSTEM
    SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
    VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",
    MANAGE_SETTINGS: "MANAGE_SETTINGS",
};

module.exports = { PERMISSIONS };
